<h4> Course 3 Week 1 </h4>

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

In [7]:

sentences =[
    'I love my dog',
    'I love my cat',
    'You love my dog!',
]

tokenizer = Tokenizer(num_words=100) # top 100 volume words
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print(word_index)

{'love': 1, 'my': 2, 'i': 3, 'dog': 4, 'cat': 5, 'you': 6}


In [12]:
sentences =[
    'I love my dog',
    'I love my cat',
    'You love my dog!',
    'Do you think my dog is amazing?',
]

tokenizer = Tokenizer(num_words=100) # top 100 volume words
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
#text to sequence
sequences = tokenizer.texts_to_sequences(sentences)

print(word_index)
print(sequences)

test_data =[
     'I really love my dog',
     'my dog loves my mantee'
]
test_seq = tokenizer.texts_to_sequences(test_data)
# word "really" is lost cz there is not in dict
print(test_seq)


{'my': 1, 'love': 2, 'dog': 3, 'i': 4, 'you': 5, 'cat': 6, 'do': 7, 'think': 8, 'is': 9, 'amazing': 10}
[[4, 2, 1, 3], [4, 2, 1, 6], [5, 2, 1, 3], [7, 5, 8, 1, 3, 9, 10]]
[[4, 2, 1, 3], [1, 3, 1]]


In [13]:
sentences =[
    'I love my dog',
    'I love my cat',
    'You love my dog!',
    'Do you think my dog is amazing?',
]
# add a special character "<OOV>" , so words that doesnt in dict get this value
tokenizer = Tokenizer(num_words=100,oov_token="<OO>") # top 100 volume words
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
#text to sequence
sequences = tokenizer.texts_to_sequences(sentences)

print(word_index)
print(sequences)

test_data =[
     'I really love my dog',
     'my dog loves my mantee'
]
test_seq = tokenizer.texts_to_sequences(test_data)
# word "really" is lost cz there is not in dict
print(test_seq)

{'<OO>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}
[[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]
[[5, 1, 3, 2, 4], [2, 4, 1, 2, 1]]


In [15]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences =[
    'I love my dog',
    'I love my cat',
    'You love my dog!',
    'Do you think my dog is amazing?',
]
# add a special character "<OOV>" , so words that doesnt in dict get this value
tokenizer = Tokenizer(num_words=100,oov_token="<OO>") # top 100 volume words
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
#text to sequence
sequences = tokenizer.texts_to_sequences(sentences)
#padded , all senctences have the same length
padded = pad_sequences(sequences)
print(word_index)
print(sequences)
print(padded)

padded = pad_sequences(sequences,padding='post',
                       truncating='post',maxlen=5)
print(padded)


{'<OO>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}
[[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]
[[ 0  0  0  5  3  2  4]
 [ 0  0  0  5  3  2  7]
 [ 0  0  0  6  3  2  4]
 [ 8  6  9  2  4 10 11]]
[[5 3 2 4 0]
 [5 3 2 7 0]
 [6 3 2 4 0]
 [8 6 9 2 4]]


In [16]:
#SARCASM
!wget --no-check-certificate \
    https://storage.googleapis.com/laurencemoroney-blog.appspot.com/sarcasm.json \
    -O /tmp/sarcasm.json


import json

with open('sarcasm.json',r) as f:
    datastore = json.load(f)

setences = []
labels = []
urls = []
for item in datastore:
    setences.append(item['headline'])
    labels.append(item['is_sarcastic'])
    urls.append(item['article_link'])


import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


tokenizer = Tokenizer(oov_token="<OO>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

sequences = tokenizer.texts_to_sequences(sentences)
#padded , all senctences have the same length
padded = pad_sequences(sequences,padding='post')
print(padded[0])
print(padded.shape)
import csv
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


#Stopwords list from https://github.com/Yoast/YoastSEO.js/blob/develop/src/config/stopwords.js
# Convert it to a Python list and paste it here
stopwords = [ "a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", "as", "at", "be", "because", "been", "before", "being", "below", "between", "both", "but", "by", "could", "did", "do", "does", "doing", "down", "during", "each", "few", "for", "from", "further", "had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its", "itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on", "once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so", "some", "such", "than", "that", "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's", "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", "to", "too", "under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're", "we've", "were", "what", "what's", "when", "when's", "where", "where's", "which", "while", "who", "who's", "whom", "why", "why's", "with", "would", "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves" ]#YOUR CODE HERE
print(type(stopwords))

--2020-10-07 17:32:16--  https://storage.googleapis.com/laurencemoroney-blog.appspot.com/sarcasm.json
Resolving storage.googleapis.com (storage.googleapis.com)... 2a00:1450:4017:80b::2010, 2a00:1450:4017:808::2010, 2a00:1450:4017:809::2010, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|2a00:1450:4017:80b::2010|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5643545 (5.4M) [application/json]
Saving to: '/tmp/sarcasm.json'

     0K .......... .......... .......... .......... ..........  0%  774K 7s
    50K .......... .......... .......... .......... ..........  1% 1.55M 5s
   100K .......... .......... .......... .......... ..........  2% 1.57M 5s
   150K .......... .......... .......... .......... ..........  3%  597K 6s
   200K .......... .......... .......... .......... ..........  4% 2.63M 5s
   250K .......... .......... .......... .......... ..........  5% 3.19M 4s
   300K .......... .......... .......... .......... ..........  6%  666K

NameError: name 'r' is not defined

In [32]:
import csv
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


#Stopwords list from https://github.com/Yoast/YoastSEO.js/blob/develop/src/config/stopwords.js
# Convert it to a Python list and paste it here
stopwords = [ "a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", "as", "at", "be", "because", "been", "before", "being", "below", "between", "both", "but", "by", "could", "did", "do", "does", "doing", "down", "during", "each", "few", "for", "from", "further", "had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its", "itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on", "once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so", "some", "such", "than", "that", "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's", "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", "to", "too", "under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're", "we've", "were", "what", "what's", "when", "when's", "where", "where's", "which", "while", "who", "who's", "whom", "why", "why's", "with", "would", "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves" ]#YOUR CODE HERE
print(type(stopwords))
print(len(stopwords))

sentences = []
labels = []
with open("bbc-text.csv", 'r') as csvfile:
    # Your Code here
    reader = csv.reader(csvfile, delimiter=',')
    next(reader)
    for row in reader:
        labels.append(row[0])
        filtered_sentence = row[1]
        for stopword in stopwords:
            filtered_sentence=filtered_sentence.replace(' '+stopword+' ' , ' ')
        sentences.append(filtered_sentence.replace('  ',' '))


print(len(sentences))
print(sentences[0])

<class 'list'>
153
2225
tv future hands viewers home theatre systems  plasma high-definition tvs  digital video recorders moving living room  way people watch tv will radically different five years  time.  according expert panel gathered annual consumer electronics show las vegas discuss new technologies will impact one favourite pastimes. us leading trend  programmes content will delivered viewers via home networks  cable  satellite  telecoms companies  broadband service providers front rooms portable devices.  one talked-about technologies ces digital personal video recorders (dvr pvr). set-top boxes  like us s tivo uk s sky+ system  allow people record  store  play  pause forward wind tv programmes want.  essentially  technology allows much personalised tv. also built-in high-definition tv sets  big business japan us  slower take off europe lack high-definition programming. not can people forward wind adverts  can also forget abiding network channel schedules  putting together a-la-

In [34]:
!pip install -q tensorflow-datasets
import tensorflow as tf
print(tf.__version__)


2.3.1


In [36]:
import tensorflow_datasets as tfds
imdb,info = tfds.load('imdb_reviews', with_info=True, as_supervised=True)

Shuffling and writing examples to C:\Users\Alexios\tensorflow_datasets\imdb_reviews\plain_text\1.0.0.incomplete1DUK0E\imdb_reviews-train.tfrecord


Shuffling and writing examples to C:\Users\Alexios\tensorflow_datasets\imdb_reviews\plain_text\1.0.0.incomplete1DUK0E\imdb_reviews-test.tfrecord


Shuffling and writing examples to C:\Users\Alexios\tensorflow_datasets\imdb_reviews\plain_text\1.0.0.incomplete1DUK0E\imdb_reviews-unsupervised.tfrecord


Dataset imdb_reviews downloaded and prepared to C:\Users\Alexios\tensorflow_datasets\imdb_reviews\plain_text\1.0.0. Subsequent calls will reuse this data.


In [37]:
train_data, test_data = imdb['train'], imdb['test']

In [ ]:
training_setences =[]


